services:
  postgres:
    ports:
      - "5432:5432"

  redis:
    ports:
      - "6379:6379"

  backend:
    volumes:
      - ./backend:/app
    environment:
      APP_DEBUG: "true"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  bot:
    volumes:
      - ./bot:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8001 --reload

  worker:
    volumes:
      - ./backend:/app
    command: celery -A app.workers.celery_app worker --loglevel=info

  beat:
    volumes:
      - ./backend:/app
    command: celery -A app.workers.celery_app beat --loglevel=info

  frontend:
    build:
      target: dev
    volumes:
      - ./frontend:/app

  nginx:
    volumes:
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
